name: kedro-action
author: Waylon Walker
description: Run kedro project
inputs:
  python_version:
    description: a Python version that is supported by pyenv
    default: '3.7.0'
  should_lint:
    description: runs `kedro lint`
    default: true
  should_test:
    description: runs `kedro test`
    default: true
  should_build_docs:
    description: runs `kedro build-docs`
    default: true
  should_package:
    description: runs `kedro package`
    default: true
  should_run:
    description: runs `kedro run`
    default: false
  should_viz:
    description: creates a static site built on gatsby based on `kedro viz --save-pipeline pipeline.json`
    default: true
  docs_branch:
    description: branch to push docs output to
    branch: docs
  viz_branch:
    description: branch to push static viz to
    default: kedro-static-viz
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python_version }}
    - ${{ inputs.should_lint }}
    - ${{ inputs.should_test }}
    - ${{ inputs.should_build_docs }}
    - ${{ inputs.should_package }}
    - ${{ inputs.should_run }}
    - ${{ inputs.should_viz }}
    - ${{ inputs.docs_branch }}
    - ${{ inputs.viz_branch }}
branding:
  icon: 'git-branch'
  color: 'black'
