name: kedro-deployment
author: Juan Jose Alban
description: Run kedro project
inputs:
  python_version:
    description: a Python version that is supported by pyenv
    required: true
    default: '3.8'
  should_lint:
    description: runs `kedro lint`
    required: true
    default: 'true'
  should_test:
    description: runs `kedro test`
    required: true
    default: 'true'
  should_build_docs:
    description: runs `kedro build-docs`
    required: true
    default: 'true'
  should_package:
    description: runs `kedro package`
    required: true
    default: 'true'
  should_run:
    description: runs `kedro run`
    required: true
    default: 'false'
  should_viz:
    description: creates a static site built on gatsby based on `kedro viz --save-pipeline pipeline.json`
    required: true
    default: 'true'
  deploy_branch:
    description: branch to deploy static site to
    required: true
    default: gh-pages
  github_pat:
    description: >
      github personal access token
      for help see https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    required: true
    default: ''
  verbose:
    description: prints extra information for debugging
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python_version }}
    - ${{ inputs.should_lint }}
    - ${{ inputs.should_test }}
    - ${{ inputs.should_build_docs }}
    - ${{ inputs.should_package }}
    - ${{ inputs.should_run }}
    - ${{ inputs.should_viz }}
    - ${{ inputs.docs_branch }}
    - ${{ inputs.viz_branch }}
    - ${{ inputs.deploy_branch}}
    - ${{ inputs.GITHUB_PAT}}
    - ${{ inputs.verbose }}
branding:
  icon: 'git-branch'
  color: 'gray-dark'
